### ISSUE TITLE
Ingress ADDRESS not getting set on IBM Bluemix

### ISSUE THREAD

**Issue by frankbu** [istio/issues#10]
Users running the Istio Bookinfo sample on an IBM Bluemix paid cluster, which supports external loadbalancers, are noticing that the LB external IP fails to get set in the Ingress resource.  
```
kubectl get ingress -o wide
NAME      HOSTS     ADDRESS   PORTS     AGE
gateway   *                   80        9m
```
The address field is blank even though the ingress has an external ip:
```
Kubectl get svc
istio-ingress   10.10.10.204   169.47.245.10
```
The  following error appears in the istio-ingress log:
```
I0523 19:48:25.146704       1 status.go:302] updating Ingress default/gateway status to [{169.47.245.10 }]
W0523 19:48:25.149243       1 status.go:306] error updating ingress rule: Forbidden: "/apis/extensions/v1beta1/namespaces/default/ingresses/gateway/status" (put ingresses.extensions gateway)
```

**Comment by craigyam** [comment]
I tried out the latest istio-rbac-alpha.yaml and the address field in `kubectl get ingress` is still not populated.  Here's the change that I made to the yaml that seemed to fix the problem:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: istio-manager
rules:
- apiGroups: ["istio.io"]
  resources: ["istioconfigs", "istioconfigs.istio.io"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["thirdpartyresources", "thirdpartyresources.extensions", "ingresses", "ingresses/status"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "endpoints", "pods", "services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
.
.
.
```

I just added "ingresses/status" to the section above.
