### ISSUE TITLE
Cannot inject istio sidecar on kubernetes cronjobs

### ISSUE THREAD

**Issue by franzbeltran** [istio/issues#106]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Y

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.2.7
GitRevision: 6b145c189aad8306b13af1725123bebfbc7eefd4
GitBranch: master
User: root@f1eeb85f62ab
GolangVersion: go1.8.3
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not ?**
No, installed istio.yaml.

**What happened**:
Upon trying to inject istio sidecars to my cronjob, for example:
```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

Using the following command:
```
istioctl kube-inject -f cronjob.yaml
```

An error occurs:
```
panic: reflect: call of reflect.Value.FieldByName on zero Value

goroutine 1 [running]:
reflect.flag.mustBe(0x0, 0x19)
	/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/go1_8_3_linux_amd64/src/reflect/value.go:201 +0xae
reflect.Value.FieldByName(0x0, 0x0, 0x0, 0x1493a31, 0xa, 0x16, 0xc4203a4f20, 0x199)
	/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/go1_8_3_linux_amd64/src/reflect/value.go:812 +0x49
istio.io/pilot/platform/kube/inject.intoObject(0xc4203e5ad0, 0x1470ca0, 0xc4203a4500, 0x1470ca0, 0xc4203a4500, 0x0, 0x0)
	platform/kube/inject/inject.go:479 +0x396
istio.io/pilot/platform/kube/inject.IntoResourceFile(0xc4203e5ad0, 0x1bc28a0, 0xc42008e000, 0x1bc28e0, 0xc42008e008, 0x1557420, 0x5)
	platform/kube/inject/inject.go:519 +0x458
main.glob..func3(0x1c31060, 0xc420403e20, 0x0, 0x2, 0x0, 0x0)
	cmd/istioctl/inject.go:146 +0x56f
github.com/spf13/cobra.(*Command).execute(0x1c31060, 0xc420403d80, 0x2, 0x2, 0x1c31060, 0xc420403d80)
	external/com_github_spf13_cobra/command.go:650 +0x457
github.com/spf13/cobra.(*Command).ExecuteC(0x1c309a0, 0x11f74f3, 0x0, 0x0)
	external/com_github_spf13_cobra/command.go:729 +0x339
github.com/spf13/cobra.(*Command).Execute(0x1c309a0, 0x0, 0x154)
	external/com_github_spf13_cobra/command.go:688 +0x2b
main.main()
	cmd/istioctl/main.go:526 +0xc0
```

**What you expected to happen:**
The cronjob should've been created. When the cronjob's schedule is due, a job and a pod should be created containing the istio sidecar.

**How to reproduce it:**
Try to inject istio sidecar to a kubernetes cronjob

**Feature Request:**
N

**Describe the feature:**
N/A
