### ISSUE TITLE
Can't set timeout rules above 15s

### ISSUE THREAD

**Issue by kornholi** [istio/issues#116]
**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics): Y

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.2.7 - 0.2.10
kubectl version 1.7.6
```

**Is Istio Auth enabled or not?** No

httpReqTimeout doesn't work with values greater than 15s. Anything below 15s functions correctly. At first I thought it was related to ingress, but the problem remains going directly from an another Istio enabled service. It seems like the default 15s timeout isn't changed on the destination side? (`x-envoy-upstream-service-time` header disappears with a timeout rule <15s) 

```yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: foo-timeout
spec:
  destination:
    name: foo
  httpReqTimeout:
    simpleTimeout:
      timeout: 20s
```
```
HTTP/1.1 504 Gateway Timeout
content-length: 24
content-type: text/plain
date: Tue, 31 Oct 2017 19:51:38 GMT
server: envoy
x-envoy-upstream-service-time: 15007

upstream request timeout
real	0m15.025s
user	0m0.005s
sys	0m0.007s
```
