### ISSUE TITLE
Circuit breaker does not appear to work

### ISSUE THREAD

**Issue by georgeharley** [istio/issues#140]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.3.0
kubectl version 1.8.4
```
The cluster is running on GKE and was installed using the Istio GKE Deployment Manager. 

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
In the deployment manager the "Enable mutualTLS authentication" box was left checked so I assume this means Istio Auth is enabled. 

**What happened**:
There are two services running in the cluster: serviceA (which is externally accessible) and serviceB. ServiceA calls serviceB as part of its request handling logic. A simple route rule for ServiceB was created and later on a destination policy was created declaring a simple circuit breaker for ServiceB. The circuit breaker included an `httpConsecutiveErrors` value of 1. After checking that external requests to serviceA were successful and verifying that each response contained data from serviceB (confirming that serviceB was being called), serviceB was made to return an HTTP 500 internal server error response.  

**Route Rule for ServiceB**
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: bookstore-default
spec:
  destination:
    name: bookstore
  route:
  - labels:
      version: v1
    weight: 100
```

**Destination Policy for ServiceB**
```
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: bookstore-cb-policy
  namespace: default
spec:
  destination:
    name: bookstore
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 1
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpMaxPendingRequests: 1
      maxConnections: 1
      sleepWindow: 10m
```

**What you expected to happen:**
I expected to see one of serviceB's pods ejected from the load balancing pool for a period of time no shorther than the value of `sleepWindow`. What actually happened was that the pods associated with serviceB remained unchanged. I am not aware of any other way of verifying the correctness of the destination policy containing the circuit breaker other than sending traffic to the destination service and arranging for an error to be raised. 

**How to reproduce it:**
Including a cookie "fail=yes" in any external request to exposed serviceA will result in the serviceB call for that request returning an HTTP 500 response. The serviceA implementation just forwards the cookie value to serviceB. The serviceB implementation checks for the existence of the "fail=yes" cookie and if found immediately returns the 500 error, otheriwse it completes normally and returns a 200 response code. 

**Feature Request:**
N

**Describe the feature:**
N/A
