### ISSUE TITLE
SSL issue with Istio enabled microservice using EgressRules. SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

### ISSUE THREAD

**Issue by Dadabhvai-Kashyap** [istio/issues#188]
**Is this a BUG or FEATURE REQUEST?:**
I think it is a bug
**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**:
yes, no solved
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**

**istioctl version**
```Version: 0.4.0
GitRevision: 24089ea97c8d244493c93b499a666ddf4010b547-dirty
GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13
User: root@cc5c34bbd1ee
GolangVersion: go1.8
```
**kubectl version**
``` Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-12-06T20:03:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
istio.yaml - no mutual tls

**What happened**:
I using egressRules 

```
cat <<EOF | ./istioctl create -f -
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: nodeapp-egress-rule
spec:
  destination:
    service: nodeapp.mydomain.in
  ports:
    - port: 3000
      protocol: https
EOF
```
Istio enabled NodeJs app fails to establish https connection to resource outside cluster using https
`SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n"}`
Same for the curl 
`curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number`
**What you expected to happen:**
Retrieve correct result
**How to reproduce it:**
Install sample software, inject side-car and try to request external https  resource
