### ISSUE TITLE
Cannot route traffic to multiple namespaces

### ISSUE THREAD

**Issue by johanfrick-mobenga** [istio/issues#195]
**Is this a BUG or FEATURE REQUEST?:** BUG

**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version 0.5.0
kubectl version 1.7.12-gke.0
```
Followed this guide https://istio.io/docs/setup/kubernetes/quick-start.html.

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
istio.yaml

**What happened**:
In the default namespace I have deployed my standard version of the application.
I the ns-safari namespace I have deployed my slightly altered version of the application to present unique interface to safari users.
Here is my RouteRoule:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: static-server-safari
spec:
  destination:
    name: static-server
  precedence: 2
  match:
    request:
      headers:
        user-agent:
          regex: ".*Safari.*"
  route:
  - destination:
      name: static-server
      namespace: ns-safari
    weight: 100
```
I have spent days of trying out different solutions and reading the specs but it still does not work.
As soon as I add this rule I get "No healthy upstream" in all browsers. When I remove it again it works fine in all browsers, but of course the standard version of the application is shown.

Reading the specs, I believe my RouteRoule is correct, but I have not seen a single example that uses "destination" under "route".

**Feature Request:**
N

**Comment by ijsnellf** [comment]
It sounds like you have two issues:
1. Header match on `User-Agent` is not working.
2. Route to static-service in ns-safari is not working.

For 1, do you have a default routing rule of precedence 1 that directs all traffic to `static-server`? 

For 2, have you tried using the `service` field inside the route destination with the FQDN of the Safari service?:
```yaml
  route:
  - destination:
      service: static-server.ns-safari.svc.cluster.local # or whatever the appropriate FQDN is
    weight: 100
```
This might bypass any issues with routing via service name and namespace.

**Comment by johanfrick-mobenga** [comment]
This is actually working:
```yaml
  route:
  - destination:
      service: static-server.ns-safari.svc.cluster.local # or whatever the appropriate FQDN is
    weight: 100
```
Thanks a lot, @ijsnellf
