### ISSUE TITLE
The example httpapispec.yaml do not work

### ISSUE THREAD

**Issue by luguoxiang** [istio/issues#198]
**Is this a BUG or FEATURE REQUEST?:** 
a BUG
**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**:
Y
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.5.0
GitRevision: c9debceacb63a14a9ae24df433e2ec3ce1f16fc7
User: root@211b132eb7f1
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-beta.0.27+43be4eecea94fc-dirty", GitCommit:"43be4eecea94fc9fd008d0cb1045957d0d9dbfef", GitTreeState:"dirty", BuildDate:"2017-11-30T02:10:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
N
**What happened**:
I install istio 0.5.0 to kubernates 1.8 and install samples/bookinfo/kube/bookinfo.yaml 
I follow the instruction in https://istio.io/docs/reference/config/istio.mixer.v1.config.client.html to create httpapispec and httpapispecbing:
kubectl create -f  httpapispec.yaml
```yaml
apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpec
metadata:
  name: products
  namespace: default
spec:
  attributes:
      api.service: product.swagger.io
      api.version: 1.0.0
  patterns:
  - attributes:
        api.operation: getProducts
    httpMethod: GET
    uriTemplate: /productpage
```
kubectl create -f httpapispecbindings.yaml
```
apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpecBinding
metadata:
  name: products-binding
  namespace: default
spec:
  api_specs:
  - name: products
    namespace: default
  services:
  - domain: svc.cluster.local
    name: productpage
    namespace: default
```
I add  api.operation, api.service, api.version related config to istio:
kubectl get attributemanifests.config.istio.io -n istio-system kubernetes -o yaml
```yaml
apiVersion: config.istio.io/v1alpha2
kind: attributemanifest
...
spec:
  attributes:
    api.operation:
      valueType: STRING
    api.service:
      valueType: STRING
    api.version:
      valueType: STRING
```
kubectl get metrics.config.istio.io -n istio-system requestduration -o yaml
```yaml
apiVersion: config.istio.io/v1alpha2
kind: metric
spec:
  dimensions:
    api_operation: api.operation | ""
    api_service: api.service | ""
    api_version: api.version | ""
```
kubectl get prometheuses.config.istio.io -n istio-system handler -o yaml
```yaml
apiVersion: config.istio.io/v1alpha2
kind: prometheus
spec:
  metrics:
    instance_name: requestduration.metric.istio-system
    kind: DISTRIBUTION
    label_names:
    - source_service
    - source_version
    - destination_service
    - destination_version
    - response_code
    - api_operation
    - api_version
    - api_service
    - method
    - url
```

**What you expected to happen:**
After access productpage through istio-ingress http://{node ip}:{node port}/productpage
The prometheus istio_request_duration_bucket metric should contains 
api_operation="getProducts",api_service="product.swagger.io",api_version="1.0.0",
But all three field are empty.

The log of the pilot has following warning:
kubectl log istio-pilot-69cc4dd5cb-cn7bs -n istio-system  -c discovery
```
error translating object &crd.HTTPAPISpec{TypeMeta:v1.TypeMeta{Kind:"HTTPAPISpec", APIVersion:"config.istio.io/v1alpha2"}, ObjectMeta:v1.ObjectMeta{Name:"products", GenerateName:"", Namespace:"default", SelfLink:"/apis/config.istio.io/v1alpha2/namespaces/default/httpapispecs/products", UID:"c4d5514c-0fc5-11e8-9f23-0800270584d7", ResourceVersion:"1062178", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63654017072, loc:(*time.Location)(0x2b08d60)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:map[string]interface {}{"attributes":map[string]interface {}{"api.service":"product.swagger.io", "api.version":"1.0.0"}, "patterns":[]interface {}{map[string]interface {}{"attributes":map[string]interface {}{"api.operation":"getProducts"}, "httpMethod":"GET", "uriTemplate":"/api/v1/products"}}}}
```
It seems the pilot try to convert the spec part of httpapispec.yaml
 to protobuf https://github.com/istio/api:mixer/v1/config/client/api_spec.proto, but they does not match,
I changed the  httpapispec.yaml to following config, then all things worked as expected.
```yaml
apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpec
metadata:
  name: products
  namespace: default
spec:
  attributes:
    attributes:
      api.service:
        stringValue: product.swagger.io
      api.version:
        stringValue: 1.0.0
  patterns:
  - attributes:
      attributes:
        api.operation:
          stringValue: getProducts
    httpMethod: GET
    uriTemplate: /productpage
``
This seems not the expected format of httpapispec.yaml.

**How to reproduce it:**

see above 'What happened'

**Feature Request:**
N

**Describe the feature:**
--
