### ISSUE TITLE
RouteRule rewrite not working

### ISSUE THREAD

**Issue by Dadabhvai-Kashyap** [istio/issues#205]
Route rules not working for me
**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
yes
**Bug:**
Y/N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl 0.5.1
kubectl 1.7.6
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
istio.yaml
**What happened**:
Route rules not rewriting host. I do `curl  service1.com` and expect redirection to service2.com
**What you expected to happen:**
I expect to go to service1.com  and istio will rewrite me to service2.com 
**How to reproduce it:**
``` yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
 name: rewrite-rule
spec:
  destination:
    service: service1.com
  match:
    request:
      headers:
        uri:
           exact: service1.com:3000
  rewrite:
    uri: service2.com 
```

**Feature Request:**
Y/N

**Describe the feature:**

**Comment by GregHanson** [comment]
@Dadabhvai-Kashyap since you are sending traffic to an entirely different host, rather than rewriting a portion of the uri, I would use the Host header for the match header criteria and rewrite `authority` instead of `uri`

**Comment by Dadabhvai-Kashyap** [comment]
@GregHanson  I tried to match and rewrite authority headers like:
``` yaml
match:
    request:
      headers:
        authority:  service1.com:3000
  rewrite:
    authority: service2.com
```
I use `curl -iv service1.com`  and see that host header is not getting rewritten by envoy.
Could you please tell how do we test that rules are propagated properly to envoys
