### ISSUE TITLE
Conflict between tcp and https EgressRules with the same port

### ISSUE THREAD

**Issue by sbueringer** [istio/issues#215]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
kubectl version
```
0.5.1
1.9.3

**Is Istio Auth enabled or not ?**
istio-auth.yaml

**What happened**:
I want to enable access to two external services via EgressRules. The first one is accessible via https so that can be achieved with a regular https EgressRule. The second one can only be accessed with mutual TLS, so my application has to access the external service directly. Therefore, I tried to use an EgressRule with protocl tcp. Both listen on port 443. I deployed the following EgressRules:
````
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
 name: firstrule
spec:
 destination:
   service: google.com
 ports:
 - port: 443
   protocol: https
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
 name: secondrule
spec:
 destination:
   service: 55.15.87.14
 ports:
 - port: 443
   protocol: tcp
````

Unfortunately the EgressRules don't work and the following error can be found in the pilot log:
````
* rule egress-rule/default/firstrule is rejected since it conflicts rules [egress-rule/default/secondrule] on port 443, protocol HTTP vs. protocol TCP
````

**What you expected to happen:**

Both EgressRules should work together.

**How to reproduce it:**
Deploy the EgressRules from above and look at the istio-pilot log.
