### ISSUE TITLE
Timeout + Delay does not seem to work

### ISSUE THREAD

**Issue by ziggy42** [istio/issues#228]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
$ istioctl version
Version: 0.5.1
GitRevision: 30acfe6528107ea333543309095659b93364b30d
User: root@2e4a18076b04
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
No

**What happened**:
I have 3 services `frontend -> api -> gatekeeper.`
I defined a delay for the calls to gatekeeper:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: gatekeeper-test-delay
spec:
  destination:
    name: gatekeeper
  httpFault:
    delay:
      percent: 100
      fixedDelay: 10s
```

And a timeout for the calls to api:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: api-timeout
spec:
  destination:
    name: api
  httpReqTimeout:
    simpleTimeout:
      timeout: 5s
```

Calls to `frontend` are stuck "forever".

If I create just the timeout, everything works and I can't see anything because the total time of a call to `frontend` is about 0.5 s.

If I create just the delay, calls to `frontend` are 10.something s long.

**What you expected to happen:**
Calls to `frontend` should timeout after 5 seconds
