### ISSUE TITLE
RouteRule incorrectly handles routing for http-only backend

### ISSUE THREAD

**Issue by Dadabhvai-Kashyap** [istio/issues#229]
Route rules not working for me
**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
yes
**Bug:**
Y/N

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl 0.5.1
kubectl 1.7.6
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
istio.yaml
**What happened**:
Route rules rewrites hosts, but upgrades connections to https and fails. I do `curl  service1.com` and expect redirection to http://service2.com, but instead i'am being redirected to **https://** and fail.

> curl -L -I  **http**://service1.com
> HTTP/1.1 302 Found
>location: **https**://service2.com/
>server: envoy
>content-length: 0
>x-envoy-upstream-service-time: 148
>date: Mon, 26 Feb 2018 12:05:50 GMT

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to service2.com:443
**What you expected to happen:**
I expect to go to http://service1.com  and istio will rewrite me to http://service2.com 
**How to reproduce it:**
curl -LI http://service.com

``` yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
 name: rewrite-rule
spec:
  destination:
    service: service1.com
  match:
    request:
      headers:
        authority: service1.com
  rewrite:
    authority: service2.com 
```

**Feature Request:**
Y/N

**Describe the feature:**
