### ISSUE TITLE
Autoscaling fails when automatic sidecar injection is enabled.

### ISSUE THREAD

**Issue by claudenm** [istio/issues#240]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

Yes -- there are known issues with manual injection and autoscale, but nothing with automatic sidecar injection and autoscale.

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
istio auth is enabled.

**What happened**:
In a namespace with automatic sidecar injection enabled (following the instructions here: https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection), a HorizontalPodAutoscaler will not be able to scale the deployment because it is unable to get usage for the istio-proxy container.  
```
kubectl get ns -L istio-injection
NAME           STATUS    AGE       ISTIO-INJECTION
default        Active    2d        enabled
inject         Active    1h        enabled
istio-system   Active    2d        
kube-public    Active    2d        
kube-system    Active    2d        
no-inject      Active    1h        
```Injection Enabled -- Can't Scale
k describe hpa -n inject
Name:                                                  sleep
Namespace:                                             inject
Labels:                                                app=sleep
Annotations:                                           <none>
CreationTimestamp:                                     Wed, 14 Mar 2018 13:19:30 -0400
Reference:                                             Deployment/sleep
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          2
Max replicas:                                          20
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu on container istio-proxy in pod inject/sleep-5f78965bc4-bmc79
Events:
  Type     Reason                        Age               From                       Message
  ----     ------                        ----              ----                       -------
  Normal   SuccessfulRescale             7m                horizontal-pod-autoscaler  New size: 2; reason: Current number of replicas below Spec.MinReplicas
  Warning  FailedGetResourceMetric       6m (x2 over 7m)   horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from heapster
  Warning  FailedComputeMetricsReplicas  6m (x2 over 7m)   horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
  Warning  FailedComputeMetricsReplicas  1m (x10 over 6m)  horizontal-pod-autoscaler  failed to get cpu utilization: missing request for cpu on container istio-proxy in pod inject/sleep-5f78965bc4-bmc79
  Warning  FailedGetResourceMetric       1m (x11 over 6m)  horizontal-pod-autoscaler  missing request for cpu on container istio-proxy in pod inject/sleep-5f78965bc4-bmc79

```

```Injection disabled, Can Scale:
describe hpa -n no-inject
Name:                                                  sleep
Namespace:                                             no-inject
Labels:                                                app=sleep
Annotations:                                           <none>
CreationTimestamp:                                     Wed, 14 Mar 2018 13:19:35 -0400
Reference:                                             Deployment/sleep
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  0% (0) / 80%
Min replicas:                                          2
Max replicas:                                          20
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  the last scale time was sufficiently old as to warrant a new scale
  ScalingActive   True    ValidMetricFound  the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate
Events:
  Type     Reason                        Age   From                       Message
  ----     ------                        ----  ----                       -------
  Normal   SuccessfulRescale             8m    horizontal-pod-autoscaler  New size: 2; reason: Current number of replicas below Spec.MinReplicas
  Warning  FailedGetResourceMetric       7m    horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from heapster
  Warning  FailedComputeMetricsReplicas  7m    horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
```
**What you expected to happen:**
I would expect horizontal pod scaler to able to scale with or without the istio-proxy sidecar present.

**How to reproduce it:**
`kubectl create ns no-inject && kubectl create ns inject`
Enable automatic sidecar injection https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection on the inject namespace.

create the following resources in each namespace:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "500m"
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  labels:
    app: sleep
  name: sleep
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sleep
  targetCPUUtilizationPercentage: 80
```

Observe that the no-inject namespace is able to scale correctly, while the inject namespace can not.

*NOTE: Heapster must be running*

**Feature Request:**
N
