### ISSUE TITLE
Bug in mixer rule

### ISSUE THREAD

**Issue by cdelpinogeo** [istio/issues#259]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version:
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.4-gke.1", GitCommit:"10e47a740d0036a4964280bd663c8500da58e3aa", GitTreeState:"clean", BuildDate:"2018-03-13T18:00:36Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

istio.yaml

**What happened**:

I created the following mixer rule:
```
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: hellorest-handler
spec:
  status:
    code: 7
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: hellorest-denyrequest
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: hellorest-deny
spec:
  match: destination.service == hellorest.default.svc.cluster.local
  actions:
  - handler: hellorest-handler.denier
    instances: [hellorest-denyrequest.checknothing]
```
But traffic is still going to the hellorest service when accessing via the web browser.

**What you expected to happen:**

Traffic to be denied to the hellorest service.

**How to reproduce it:**

The yaml for the mixer rule is above. I have Istio setup with an ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: hellorest
          servicePort: 8080
```

And this is the manifest for the hellorest app:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hellorest
  name: hellorest
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: hellorest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hellorest
  name: hellorest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellorest
  template:
    metadata:
      labels:
        app: hellorest
    spec:
      containers:
      - name: hellorest
        image: quay.io/boundlessgeo/hellorest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: boundless-admin-pull-secret
      restartPolicy: Always
```

I did have a RouteRule in place, but I since deleted it. It did not have any affect on the result:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hellorest-default
spec:
  destination:
    name: hellorest
    namespace: default
  match:
    source:
      name: istio-ingress
      labels:
        istio: ingress
  precedence: 1
  route:
  - weight: 100
```

I can provide further information if needed. Thanks.
