### ISSUE TITLE
my service failed with 503 err and msg "upstream connect error or disconnect/reset before headers"

### ISSUE THREAD

**Issue by c52662** [istio/issues#267]
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
$istioctl version
Version: 0.6.0
GitRevision: 2cb09cdf040a8573330a127947b11e5082619895
User: root@a28f609ab931
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

$kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
kubectl 1.8.3
```

**Is Istio Auth enabled or not ?**
No(disabled)

**What happened**:
The official sample BookInfo worked fine on my cluster. I have written my own service named "hello-test" in python and manually injected istio sidecar (enovy-debug).  

Now I'm trying to deploy two instances of "hello-test" hoping every one sends a hello message(in HTTP GET request) to each other and waits response from peer.

_**But I get the http 503 response and error message "upstream connect error or disconnect/reset before headers".**_ 

BTW, they work fine if I run two instances directly in K8s cluster whitout any istio sidecar, so i guess it has nothing to do with my code or service.yaml config file 

Is this an envoy config issue? Or some other?
Can someone please take a look?

Thanks!
**What you expected to happen:**
my hello-test instances can receive messages from each other and send back to peer

**How to reproduce it:**
use the following yaml configure to deploy my hello-test.py 

**Feature Request:**
N

### Here is the yaml file content of my service before injection:
```yaml
######################################################  
#one instance named hello-test-a   ---- service-a.yaml
###################################################### 
apiVersion: v1
kind: Service
metadata:
  name: hello-test-a
  namespace: default
  labels:
    app: hello-test-a
spec:
  selector:
    app: hello-test-a
  ports:
  - name: http
    port: 41302
    targetPort: 41302    
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-test-a
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-test-a
        version: v1
    spec:
      nodeSelector:
        kaml: support
      containers:
      - name: hello-test-a
        image: capu-svr:5000/hello-test
        command: ["/bin/bash"]
        args:
        - -c
        - cd /home/capu/dist/hello-test; ./hello-test hello-test-a hello-test-b
        ports:
        - containerPort: 41302        
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-test-a
  annotations:
    kubernetes.io/ingress.class: "istio"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /123/req-from-hello-test-b
        backend:
          serviceName: hello-test-a
          servicePort: 41302
---
######################################################  
#the other instance named hello-test-b   ---- service-b.yaml
###################################################### 
apiVersion: v1
kind: Service
metadata:
  name: hello-test-b
  namespace: default
  labels:
    app: hello-test-b
spec:
  selector:
    app: hello-test-b
  ports:
  - name: http
    port: 41302
    targetPort: 41302
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-test-b
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-test-b
        version: v1
    spec:
      nodeSelector:
        kaml: support
      containers:
      - name: hello-test-b
        image: capu-svr:5000/hello-test
        command: ["/bin/bash"]
        args:
        - -c
        - cd /home/capu/dist/hello-test; ./hello-test hello-test-b hello-test-a
        ports:
        - containerPort: 41302        
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-test-b
  annotations:
    kubernetes.io/ingress.class: "istio"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /123/req-from-hello-test-a
        backend:
          serviceName: hello-test-b
          servicePort: 41302
---
```
### Here is the code of hello-test:
```python
#!/usr/bin/env python
import sys
import socket
import logging
import requests
import time
import threading
import BaseHTTPServer

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s - %(message)s',
                    datefmt="%Y-%m-%d %H:%M:%S")

selfName = sys.argv[1]
peerName = sys.argv[2]
g_port = 41302

class PackHandle(BaseHTTPServer.BaseHTTPRequestHandler):
    global selfName
    global peerName
    
    protocol_version = 'HTTP/1.1'
        
    def do_GET(self):        
        if self.path.startswith("/123/"):
            logging.debug("url match")
            self.send_response(200)
            self.do_something()
        else:
            logging.debug("url not match")
            self.send_error(400)

    def do_something(self):
        logging.debug("service[%s] recv request[%s]" % (selfName, self.path))
        self.end_headers()
        self.wfile.write("service[%s] send response for [%s]\n\n\n" % (selfName, self.path))


myname = socket.getfqdn(socket.gethostname())
g_selfAddr = socket.gethostbyname(myname)
logging.debug("now get self addr = %s" % g_selfAddr)


#recv req from peer and send response
def ThdChipPackServ():
    logging.debug("start server %s at %s..." % (selfName, g_selfAddr))
    server = BaseHTTPServer.HTTPServer((g_selfAddr, g_port), PackHandle)
    server.serve_forever()
curThread = threading.Thread(name="ThdChipPackServ", target=ThdChipPackServ)
curThread.setDaemon(True)
curThread.start()


#send req to peer to get response
while 1:
    time.sleep(5)
    response = requests.get("http://%s:%s/123/req-from-%s" % (peerName, g_port, selfName))   
    logging.info(response)
    logging.info(response.text)
```    
### Here is the log of hello-test-a  instance :
```
2018-04-04 05:42:15 hello-test.py[line:41] DEBUG - now get self addr = 172.0.86.5
2018-04-04 05:42:15 hello-test.py[line:46] DEBUG - start server hello-test-a at 172.0.86.5...
2018-04-04 05:42:20 connectionpool.py[line:213] INFO - Starting new HTTP connection (1): hello-test-b
2018-04-04 05:42:20 connectionpool.py[line:395] DEBUG - "GET /123/req-from-hello-test-a HTTP/1.1" 503 57
2018-04-04 05:42:20 hello-test.py[line:58] INFO - <Response [503]>
2018-04-04 05:42:20 hello-test.py[line:59] INFO - upstream connect error or disconnect/reset before headers
2018-04-04 05:42:25 connectionpool.py[line:213] INFO - Starting new HTTP connection (1): hello-test-b
2018-04-04 05:42:25 connectionpool.py[line:395] DEBUG - "GET /123/req-from-hello-test-a HTTP/1.1" 503 57
2018-04-04 05:42:25 hello-test.py[line:58] INFO - <Response [503]>
2018-04-04 05:42:25 hello-test.py[line:59] INFO - upstream connect error or disconnect/reset before headers
2018-04-04 05:42:30 connectionpool.py[line:213] INFO - Starting new HTTP connection (1): hello-test-b
2018-04-04 05:42:30 connectionpool.py[line:395] DEBUG - "GET /123/req-from-hello-test-a HTTP/1.1" 503 57
2018-04-04 05:42:30 hello-test.py[line:58] INFO - <Response [503]>
2018-04-04 05:42:30 hello-test.py[line:59] INFO - upstream connect error or disconnect/reset before headers
......
......
......
```
