### ISSUE TITLE
istioctl -o flag does not work

### ISSUE THREAD

**Issue by FuzzOli87** [istio/issues#27]
Using Deployment file:
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: test-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: test-app
    spec:
      containers:
      - image: test/image
        name: test-app
        ports:
         - containerPort: 3000
           name: testapp
```

Executing command:
```bash
istioctl kube-inject -f deployment.yml -o istio-deployment.yml
```

Creates the istio-deployment.yml file but with no content.

**Comment by frankbu** [comment]
Works for me. Do you have istio running and using the the istioctl binary that matches?
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: test-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: injected
        alpha.istio.io/version: jenkins@ubuntu-16-04-build-12ac793f80be71-0.1.6-dab2033
        pod.beta.kubernetes.io/init-containers: '[{"args":["-p","15001","-u","1337"],"image":"docker.io/istio/init:0.1","imagePullPolicy":"Always","name":"init","securityContext":{"capabilities":{"add":["NET_ADMIN"]}}},{"args":["-c","sysctl
          -w kernel.core_pattern=/tmp/core.%e.%p.%t \u0026\u0026 ulimit -c unlimited"],"command":["/bin/sh"],"image":"alpine","imagePullPolicy":"Always","name":"enable-core-dump","securityContext":{"privileged":true}}]'
      creationTimestamp: null
      labels:
        name: test-app
    spec:
      containers:
      - image: test/image
        name: test-app
        ports:
        - containerPort: 3000
          name: testapp
        resources: {}
      - args:
        - proxy
        - sidecar
        - -v
        - "2"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: docker.io/istio/proxy_debug:0.1
        imagePullPolicy: Always
        name: proxy
        resources: {}
        securityContext:
          runAsUser: 1337
status: {}
---
```
