### ISSUE TITLE
no matches for kind "redisquota" in version "config.istio.io/v1alpha2"

### ISSUE THREAD

**Issue by fleeto** [istio/issues#287]
**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**

```
istioctl version: 0.7.1
kubectl version: 1.10.1
kubernetes version: 1.8.11
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.

No

**What happened**:

```
error: unable to recognize "ratelimit-handler.yaml": no matches for kind "redisquota" in version "config.istio.io/v1alpha2"
```

**What you expected to happen:**

maybe 

```
redisquota.config.istio.io "handler" created
```

**How to reproduce it:**

```yaml
apiVersion: config.istio.io/v1alpha2
kind: redisquota
metadata:
  name: handler
spec:
  redisServerUrl: localhost:6379
  connectionPoolSize: 10
  quotas:
    - name: requestCount.quota.istio-system
      maxAmount: 50
      validDuration: 60s
      bucketDuration: 1s
      rateLimitAlgorithm: ROLLING_WINDOW
      overrides:
        - dimensions:
            destination: ratings
            source: reviews
          maxAmount: 12
        - dimensions:
            destination: reviews
          maxAmount: 5
```

**Feature Request:**
N

**Describe the feature:**
