### ISSUE TITLE
destination-policy: LEASTCONN and ROUNDROBIN loadbalancing policies not working.

### ISSUE THREAD

**Issue by kelseyhightower** [istio/issues#33]
I'm running istio 0.1.6 and I'm unable to get the LEASTCONN or ROUNDROBIN destination policies to work. However, the RANDOM destination policy works as expected.

### Reproducing the Issue

Create the destination-policy using the `ROUNDROBIN` loadbalancing policy:

```
type: destination-policy
name: foo-roundrobin
spec:
  destination: foo.default.svc.cluster.local
  policy:
    - loadBalancing:
        name: ROUNDROBIN
```

Submit the destination policy to the `istio-pilot`:

```
istioctl create -f destination-policies/foo-round-robin.yaml
```

Notice the error from the `istioctl create` command:

```
Error: the server rejected our request for an unknown reason
```

### Logs from the `istio-pilot` service:

```
cannot parse proto message: unknown value "ROUNDROBIN" for enum istio.proxy.v1.config.LoadBalancing_SimpleLBPolicy
```
