### ISSUE TITLE
Istio 0.7.1 - Simplest VirtualService not working

### ISSUE THREAD

**Issue by emedina** [istio/issues#347]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
```

**Is Istio Auth enabled or not ?**
No Auth

**What happened**:
https://groups.google.com/forum/#!topic/istio-users/TZcW8vfc3zs

**What you expected to happen:**
https://groups.google.com/forum/#!topic/istio-users/TZcW8vfc3zs

**How to reproduce it:**
https://groups.google.com/forum/#!topic/istio-users/TZcW8vfc3zs

**Comment by emedina** [comment]
Also not working in 0.8 daily build from 22/05/2018:

https://gcsweb.istio.io/gcs/istio-release-pipeline-data/daily-build/release-0.8-20180521-15-16/

**Comment by ymesika** [comment]
This is an interesting issue. I spent some time too trying to figure out why it doesn't work.
Although I don't have a solution I will try to summarise my findings.

1. Structure similar to your original (just moved to the timeout):

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
      weight: 50
    timeout: 5s
  - route:
    - destination:
        host: httpbin
        subset: v2
      weight: 50
```

Result: the second route is never reached therefore I always get timeout.
But reading carefully [the doc](https://preliminary.istio.io/docs/concepts/traffic-management/rules-configuration.html#http-route-rules-have-precedence) I found out that it is actually the expected behaviour:

> When there are multiple rules for a given destination, they are evaluated in the order they appear in the VirtualService, i.e., the first rule in the list has highest priority.

So it doesn't reach the second destination because it has _lower_ priority.

On the other hand:

2. Changed to 50% traffic routing:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
      weight: 50
    - destination:
        host: httpbin
        subset: v2
      weight: 50
    timeout: 5s
```

In this case the traffic is indeed routed between the two versions however a `timeout` is a route object field therefore affects both.

I hope that this explains why you (and I) experienced that weird behaviour.

May personal takeaway - We may want to add a `timeout` field to the the DestignationWeight struct as well.

/cc @rshriram

**Comment by ZackButcher** [comment]
If we add in the `match` field that's omitted above and re-order the `timeout` field, hopefully it's a bit more clear how the config is laid out:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  # First HTTPRoute
  - match:
      # the empty match is `true`
    timeout: 5s
    route:
    - destination:
        host: httpbin
        subset: v1
      weight: 50
  # Second HTTPRoute
  - match:
      # the empty match is `true`
    route:
    - destination:
        host: httpbin
        subset: v2
      weight: 50
```
`First HTTPRoute`'s `match` always evaluates to `true`, and we always evaluate the [`HTTPRoute`](https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html#HTTPRoute)s in order, so we never reach `Second HTTPRoute`. Also, the timeout is part of `First HTTPRoute`, which we always match, so we always experience the timeout.

And looking at the second config:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  # First HTTPRoute
  - match:
      # the empty match is `true`
    timeout: 5s
    route:
    - destination:
        host: httpbin
        subset: v1
      weight: 50
    - destination:
        host: httpbin
        subset: v2
      weight: 50
```

Here the semantics are different than above: the destination weights are under the same `match`, so they interact with each other. Second, we see that the timeout applies to both branches.

I'm not sure if there's an easy way to define a timeout for only half of the traffic.
