### ISSUE TITLE
404 trying to route kubernetes ingress host:

### ISSUE THREAD

**Issue by dmcqueen** [istio/issues#35]
trying to get basic kubernetes ingress routing on host:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: docs.testna.me
    http:
       paths:
       - backend:
           serviceName: docs
           servicePort: 8889
```

getting 

[2017-06-15T20:51:27.033Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "172.17.0.1" "curl/7.43.0" "300e8073-b30a-9f3c-9bbe-d922b893516e" "docs.testna.me:30794" "-"

service works fine with path routing... what am I missing?

**Comment by frankbu** [comment]
It should work. Can you provide more details about what the "docs" service does, and show what worked and what didn't? e.g., the path version of ingress and corresponding curl command that worked, and the curl command that doesn't work with the host version.

**Comment by dmcqueen** [comment]
The docs service just returns html. 

This config works
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: docs
          servicePort: 8889
```

returns 

curl -v docs.testna.me:30794/
*   Trying 192.168.64.48...
* Connected to docs.testna.me (192.168.64.48) port 30794 (#0)
> GET / HTTP/1.1
> Host: docs.testna.me:30794
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< x-powered-by: Express
< accept-ranges: bytes
< cache-control: public, max-age=0
< last-modified: Thu, 15 Jun 2017 16:39:41 GMT
< etag: W/"552d-15cac9fecc8"
< content-type: text/html; charset=UTF-8
< content-length: 21805
< date: Fri, 16 Jun 2017 15:49:02 GMT
< x-envoy-upstream-service-time: 1
< server: envoy
< 
<!DOCTYPE html><html><head>......

istio-ingress logs

[2017-06-16T15:49:03.168Z] "GET / HTTP/1.1" 200 - 0 21805 2 1 "172.17.0.1" "curl/7.43.0" "1607e19f-0c0f-9502-b51a-31c251d1e446" "docs.testna.me:30794" "172.17.0.5:8889"


with the host config'ed

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: docs.testna.me
    http:
       paths:
       - backend:
           serviceName: docs
           servicePort: 8889
```

curl -v docs.testna.me:30794/
*   Trying 192.168.64.48...
* Connected to docs.testna.me (192.168.64.48) port 30794 (#0)
> GET / HTTP/1.1
> Host: docs.testna.me:30794
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Fri, 16 Jun 2017 15:54:00 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host docs.testna.me left intact


docs service looks like

```
kubectl get svc docs -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-06-15T16:40:19Z
  labels:
    app: docs
    chart: docs-0.1.0
  name: docs
  namespace: default
  resourceVersion: "11236"
  selfLink: /api/v1/namespaces/default/services/docs
  uid: 51931125-51e9-11e7-b4ea-964e270ccf32
spec:
  clusterIP: 10.0.0.201
  ports:
  - name: http
    port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app: docs
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by frankbu** [comment]
Looks like the port is part of the Host header in the curl output:
```
> Host: docs.testna.me:30794
```
Does `curl -v -H "Host: docs.testna.me" docs.testna.me:30794/` work?

**Comment by dmcqueen** [comment]
Seems like requiring port number is valid to the kube ingress spec

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: docs.testna.me:32139
    http:
       paths:
       - backend:
           serviceName: docs
           servicePort: 8889
```

kubectl create -f router.yaml 
The Ingress "gateway" is invalid: spec.rules[0].host: Invalid value: "docs.testna.me:32139": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
