### ISSUE TITLE
Istio ingress not working with given host

### ISSUE THREAD

**Issue by ronakpandya7** [istio/issues#359]
**Is this a BUG or FEATURE REQUEST?:**
BUG

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version

Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0+coreos.0", GitCommit:"6bb2e725fc2876cd94b3900fc57a1c98ca87a08b", GitTreeState:"clean", BuildDate:"2018-04-02T16:49:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Is Istio Auth enabled or not ?**
yes

**What happened**:

We are using istio ingress controller and created one istio ingress controller:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: nginx-ingress
 annotations:
   kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: myistio.com
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: migratesvc
          servicePort: 80
```
Now when I am browsing "http://myistio.com/migrate/healthcheck" it will give preoper response and that is true.
But when i am browsing "http://myistio1.com/migrate/healthcheck" it will also give proper response but that is not true as only one domain is allow that is "myistio.com" as per our ingress configuration.

**What you expected to happen:**

`"http://myistio1.com/migrate/healthcheck" should not have to work as we are not allowing "myistio1.com" host in ingress.
`

Any help?
