### ISSUE TITLE
istio 0.2.4 external service via endpoint responds with no upstream available

### ISSUE THREAD

**Issue by robertfreund** [istio/issues#81]
I would expect external service to be available. What is recommended way to target an external via service with an ip? I have found https://github.com/istio/pilot/issues/67 which seems a bit related.

If I manually pass in the IP address it works fine in desired service.

```
[2017-09-28 18:43:34.645][16][warning][http] src/envoy/mixer/mixer_control.cc:419] Could not convert to ip: source.ip: 
[2017-09-28T18:43:34.648Z] "GET /stuff HTTP/1.1" 503 UH 0 19 0 - "-" "Go-http-client/1.1" "4f04925c-c732-9570-8031-7d0537871b3e" "exservice:8080" "-"
```
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-18T20:30:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: exservice
  labels:
    app:  exservice
spec:
  ports:
    - name: http
      port: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name:  exservice
subsets:
  - addresses:
      - ip:  192.168.x.x
    ports:
      - port: 8080
```
