### ISSUE TITLE
Ingress Rules not working in custom namespace

### ISSUE THREAD

**Issue by emedina** [istio/issues#83]
**Bug:**
Y

```
istioctl version
Version: 0.2.4
GitRevision: 9c7c291eab0a522f8033decd0f5b031f5ed0e126
GitBranch: master
User: root@822a7ac3ca86
GolangVersion: go1.8.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Auth not enabled**

**What happened**:

I have defined an Ingress rule like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ag-helper-ingress
  namespace: ag-helper
spec:
  rules:
  - host: aghelper.arch.oami.eu
    http:
      paths:
      - backend:
          serviceName: ag-source-helper-service
          servicePort: 80
        path: /source.*
      - backend:
          serviceName: ag-processor-helper-service
          servicePort: 80
        path: /processor.*
      - backend:
          serviceName: ag-sink-helper-service
          servicePort: 80
        path: /sink.*
      - backend:
          serviceName: ag-ui-helper-service
          servicePort: 80
        path: /ui.*
```

Double-checked that all services belong in the `ag-helper` namespace, but I always get a 404.

On the other side, the `echoheaders` sample in the `default` namespace works fine.

**What you expected to happen:**
Ingress Rules working fine as long as the services are properly defined in the same namespace, which is my case.

**How to reproduce it:**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: simple-ingress
  namespace: whatevernamespacedifferentfromdefault
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: echoheaders
          servicePort: 80
        path: /headers.*
```

Calling it always returns 404.
